/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9-dev */

#ifndef PB_DOMSG_PB_H_INCLUDED
#define PB_DOMSG_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _Do {
  pb_callback_t inst;
  int32_t value;
} Do;

#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define Do_init_default                                                        \
  { {{NULL}, NULL}, 0 }
#define Do_init_zero                                                           \
  { {{NULL}, NULL}, 0 }

/* Field tags (for use in manual encoding/decoding) */
#define Do_inst_tag 1
#define Do_value_tag 2

/* Struct field encoding specification for nanopb */
#define Do_FIELDLIST(X, a)                                                     \
  X(a, CALLBACK, SINGULAR, STRING, inst, 1)                                    \
  X(a, STATIC, SINGULAR, INT32, value, 2)
#define Do_CALLBACK pb_default_field_callback
#define Do_DEFAULT NULL

extern const pb_msgdesc_t Do_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define Do_fields &Do_msg

/* Maximum encoded size of messages (where known) */
/* Do_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
