/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9-dev */

#include "pump_control_data.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(pump_TimeRange, pump_TimeRange, AUTO)


PB_BIND(pump_ControlData, pump_ControlData, AUTO)




