/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9-dev */

#ifndef PB_PROTOC_STR_NUM_MSG_PB_H_INCLUDED
#define PB_PROTOC_STR_NUM_MSG_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _num {
  uint32_t key;
  float value;
} num;

typedef struct _numlst {
  pb_callback_t numbers;
} numlst;

typedef struct _str {
  uint32_t key;
  pb_callback_t value;
} str;

typedef struct _strlst {
  pb_callback_t str;
} strlst;

typedef struct _strnum {
  uint32_t key;
  pb_callback_t str;
  float num;
} strnum;

typedef struct _strnumlst {
  pb_callback_t str_nums;
} strnumlst;

#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define num_init_default                                                       \
  { 0, 0 }
#define numlst_init_default                                                    \
  {                                                                            \
    { {NULL}, NULL }                                                           \
  }
#define str_init_default                                                       \
  {                                                                            \
    0, { {NULL}, NULL }                                                        \
  }
#define strlst_init_default                                                    \
  {                                                                            \
    { {NULL}, NULL }                                                           \
  }
#define strnum_init_default                                                    \
  { 0, {{NULL}, NULL}, 0 }
#define strnumlst_init_default                                                 \
  {                                                                            \
    { {NULL}, NULL }                                                           \
  }
#define num_init_zero                                                          \
  { 0, 0 }
#define numlst_init_zero                                                       \
  {                                                                            \
    { {NULL}, NULL }                                                           \
  }
#define str_init_zero                                                          \
  {                                                                            \
    0, { {NULL}, NULL }                                                        \
  }
#define strlst_init_zero                                                       \
  {                                                                            \
    { {NULL}, NULL }                                                           \
  }
#define strnum_init_zero                                                       \
  { 0, {{NULL}, NULL}, 0 }
#define strnumlst_init_zero                                                    \
  {                                                                            \
    { {NULL}, NULL }                                                           \
  }

/* Field tags (for use in manual encoding/decoding) */
#define num_key_tag 1
#define num_value_tag 2
#define numlst_numbers_tag 1
#define str_key_tag 1
#define str_value_tag 2
#define strlst_str_tag 1
#define strnum_key_tag 1
#define strnum_str_tag 2
#define strnum_num_tag 3
#define strnumlst_str_nums_tag 1

/* Struct field encoding specification for nanopb */
#define num_FIELDLIST(X, a)                                                    \
  X(a, STATIC, SINGULAR, UINT32, key, 1)                                       \
  X(a, STATIC, SINGULAR, FLOAT, value, 2)
#define num_CALLBACK NULL
#define num_DEFAULT NULL

#define numlst_FIELDLIST(X, a) X(a, CALLBACK, REPEATED, MESSAGE, numbers, 1)
#define numlst_CALLBACK pb_default_field_callback
#define numlst_DEFAULT NULL
#define numlst_numbers_MSGTYPE num

#define str_FIELDLIST(X, a)                                                    \
  X(a, STATIC, SINGULAR, UINT32, key, 1)                                       \
  X(a, CALLBACK, SINGULAR, STRING, value, 2)
#define str_CALLBACK pb_default_field_callback
#define str_DEFAULT NULL

#define strlst_FIELDLIST(X, a) X(a, CALLBACK, REPEATED, STRING, str, 1)
#define strlst_CALLBACK pb_default_field_callback
#define strlst_DEFAULT NULL

#define strnum_FIELDLIST(X, a)                                                 \
  X(a, STATIC, SINGULAR, UINT32, key, 1)                                       \
  X(a, CALLBACK, SINGULAR, STRING, str, 2)                                     \
  X(a, STATIC, SINGULAR, FLOAT, num, 3)
#define strnum_CALLBACK pb_default_field_callback
#define strnum_DEFAULT NULL

#define strnumlst_FIELDLIST(X, a) X(a, CALLBACK, REPEATED, MESSAGE, str_nums, 1)
#define strnumlst_CALLBACK pb_default_field_callback
#define strnumlst_DEFAULT NULL
#define strnumlst_str_nums_MSGTYPE strnum

extern const pb_msgdesc_t num_msg;
extern const pb_msgdesc_t numlst_msg;
extern const pb_msgdesc_t str_msg;
extern const pb_msgdesc_t strlst_msg;
extern const pb_msgdesc_t strnum_msg;
extern const pb_msgdesc_t strnumlst_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define num_fields &num_msg
#define numlst_fields &numlst_msg
#define str_fields &str_msg
#define strlst_fields &strlst_msg
#define strnum_fields &strnum_msg
#define strnumlst_fields &strnumlst_msg

/* Maximum encoded size of messages (where known) */
/* numlst_size depends on runtime parameters */
/* str_size depends on runtime parameters */
/* strlst_size depends on runtime parameters */
/* strnum_size depends on runtime parameters */
/* strnumlst_size depends on runtime parameters */
#define PROTOC_STR_NUM_MSG_PB_H_MAX_SIZE num_size
#define num_size 11

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
