/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9-dev */

#include "./str_num_msg.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(num, num, AUTO)


PB_BIND(numlst, numlst, AUTO)


PB_BIND(str, str, AUTO)


PB_BIND(strlst, strlst, AUTO)


PB_BIND(strnum, strnum, AUTO)


PB_BIND(strnumlst, strnumlst, AUTO)



