/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9-dev */

#include "./str_num_msg.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(Num, Num, AUTO)


PB_BIND(Numlist, Numlist, AUTO)


PB_BIND(Str, Str, AUTO)


PB_BIND(Strnum, Strnum, AUTO)


PB_BIND(Auth, Auth, AUTO)



