/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9-dev */

#ifndef PB_PROTOC_STR_NUM_MSG_PB_H_INCLUDED
#define PB_PROTOC_STR_NUM_MSG_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _Num {
    uint32_t key;
    float value;
} Num;

typedef struct _Numlist {
    pb_callback_t numbers;
} Numlist;

typedef struct _Str {
    uint32_t key;
    pb_callback_t value;
} Str;

typedef struct _Strlist {
    pb_callback_t strings;
} Strlist;

typedef struct _Stringlist {
    pb_callback_t strs;
} Stringlist;

typedef struct _Strnum {
    uint32_t key;
    pb_callback_t str;
    float num;
} Strnum;

typedef struct _Strnumlist {
    pb_callback_t strnums;
} Strnumlist;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define Num_init_default                         {0, 0}
#define Numlist_init_default                     {{{NULL}, NULL}}
#define Str_init_default                         {0, {{NULL}, NULL}}
#define Strlist_init_default                     {{{NULL}, NULL}}
#define Stringlist_init_default                  {{{NULL}, NULL}}
#define Strnum_init_default                      {0, {{NULL}, NULL}, 0}
#define Strnumlist_init_default                  {{{NULL}, NULL}}
#define Num_init_zero                            {0, 0}
#define Numlist_init_zero                        {{{NULL}, NULL}}
#define Str_init_zero                            {0, {{NULL}, NULL}}
#define Strlist_init_zero                        {{{NULL}, NULL}}
#define Stringlist_init_zero                     {{{NULL}, NULL}}
#define Strnum_init_zero                         {0, {{NULL}, NULL}, 0}
#define Strnumlist_init_zero                     {{{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define Num_key_tag                              1
#define Num_value_tag                            2
#define Numlist_numbers_tag                      1
#define Str_key_tag                              1
#define Str_value_tag                            2
#define Strlist_strings_tag                      1
#define Stringlist_strs_tag                      1
#define Strnum_key_tag                           1
#define Strnum_str_tag                           2
#define Strnum_num_tag                           3
#define Strnumlist_strnums_tag                   1

/* Struct field encoding specification for nanopb */
#define Num_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   key,               1) \
X(a, STATIC,   SINGULAR, FLOAT,    value,             2)
#define Num_CALLBACK NULL
#define Num_DEFAULT NULL

#define Numlist_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  numbers,           1)
#define Numlist_CALLBACK pb_default_field_callback
#define Numlist_DEFAULT NULL
#define Numlist_numbers_MSGTYPE Num

#define Str_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   key,               1) \
X(a, CALLBACK, SINGULAR, STRING,   value,             2)
#define Str_CALLBACK pb_default_field_callback
#define Str_DEFAULT NULL

#define Strlist_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  strings,           1)
#define Strlist_CALLBACK pb_default_field_callback
#define Strlist_DEFAULT NULL
#define Strlist_strings_MSGTYPE Str

#define Stringlist_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, STRING,   strs,              1)
#define Stringlist_CALLBACK pb_default_field_callback
#define Stringlist_DEFAULT NULL

#define Strnum_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   key,               1) \
X(a, CALLBACK, SINGULAR, STRING,   str,               2) \
X(a, STATIC,   SINGULAR, FLOAT,    num,               3)
#define Strnum_CALLBACK pb_default_field_callback
#define Strnum_DEFAULT NULL

#define Strnumlist_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  strnums,           1)
#define Strnumlist_CALLBACK pb_default_field_callback
#define Strnumlist_DEFAULT NULL
#define Strnumlist_strnums_MSGTYPE Strnum

extern const pb_msgdesc_t Num_msg;
extern const pb_msgdesc_t Numlist_msg;
extern const pb_msgdesc_t Str_msg;
extern const pb_msgdesc_t Strlist_msg;
extern const pb_msgdesc_t Stringlist_msg;
extern const pb_msgdesc_t Strnum_msg;
extern const pb_msgdesc_t Strnumlist_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define Num_fields &Num_msg
#define Numlist_fields &Numlist_msg
#define Str_fields &Str_msg
#define Strlist_fields &Strlist_msg
#define Stringlist_fields &Stringlist_msg
#define Strnum_fields &Strnum_msg
#define Strnumlist_fields &Strnumlist_msg

/* Maximum encoded size of messages (where known) */
/* Numlist_size depends on runtime parameters */
/* Str_size depends on runtime parameters */
/* Strlist_size depends on runtime parameters */
/* Stringlist_size depends on runtime parameters */
/* Strnum_size depends on runtime parameters */
/* Strnumlist_size depends on runtime parameters */
#define Num_size                                 11
#define PROTOC_STR_NUM_MSG_PB_H_MAX_SIZE         Num_size

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
