/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9-dev */

#ifndef PB_PROTOC_DOMSGID_PB_H_INCLUDED
#define PB_PROTOC_DOMSGID_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _DoId {
  uint32_t id;
  float value;
} DoId;

#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define DoId_init_default                                                      \
  { 0, 0 }
#define DoId_init_zero                                                         \
  { 0, 0 }

/* Field tags (for use in manual encoding/decoding) */
#define DoId_id_tag 1
#define DoId_value_tag 2

/* Struct field encoding specification for nanopb */
#define DoId_FIELDLIST(X, a)                                                   \
  X(a, STATIC, SINGULAR, UINT32, id, 1)                                        \
  X(a, STATIC, SINGULAR, FLOAT, value, 2)
#define DoId_CALLBACK NULL
#define DoId_DEFAULT NULL

extern const pb_msgdesc_t DoId_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define DoId_fields &DoId_msg

/* Maximum encoded size of messages (where known) */
#define DoId_size 11
#define PROTOC_DOMSGID_PB_H_MAX_SIZE DoId_size

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
