/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9-dev */

#include "protoc/msg1.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(Msg1, Msg1, AUTO)



