/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9-dev */

#ifndef PB_PROTOC_MSG1_PB_H_INCLUDED
#define PB_PROTOC_MSG1_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _Msg1 {
  float f0;
  float f1;
  float f2;
  float f3;
  float f4;
} Msg1;

#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define Msg1_init_default                                                      \
  { 0, 0, 0, 0, 0 }
#define Msg1_init_zero                                                         \
  { 0, 0, 0, 0, 0 }

/* Field tags (for use in manual encoding/decoding) */
#define Msg1_f0_tag 1
#define Msg1_f1_tag 2
#define Msg1_f2_tag 3
#define Msg1_f3_tag 4
#define Msg1_f4_tag 5

/* Struct field encoding specification for nanopb */
#define Msg1_FIELDLIST(X, a)                                                   \
  X(a, STATIC, SINGULAR, FLOAT, f0, 1)                                         \
  X(a, STATIC, SINGULAR, FLOAT, f1, 2)                                         \
  X(a, STATIC, SINGULAR, FLOAT, f2, 3)                                         \
  X(a, STATIC, SINGULAR, FLOAT, f3, 4)                                         \
  X(a, STATIC, SINGULAR, FLOAT, f4, 5)
#define Msg1_CALLBACK NULL
#define Msg1_DEFAULT NULL

extern const pb_msgdesc_t Msg1_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define Msg1_fields &Msg1_msg

/* Maximum encoded size of messages (where known) */
#define Msg1_size 25
#define PROTOC_MSG1_PB_H_MAX_SIZE Msg1_size

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
